package com.cse.alert.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

enum class AlertCondition { ABOVE, BELOW }

enum class AlertStatus { ACTIVE, TRIGGERED, SNOOZED, DISABLED }

@Entity(tableName = "price_alerts")
data class PriceAlert(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val symbol: String,
    val companyName: String,
    val targetPrice: Double,
    val condition: AlertCondition,
    val status: AlertStatus = AlertStatus.ACTIVE,
    val currentPrice: Double = 0.0,
    val createdAt: Long = System.currentTimeMillis(),
    val triggeredAt: Long? = null,
    val note: String = ""
)

data class CompanyInfoResponse(
    @SerializedName("reqSymbolInfo") val symbolInfo: SymbolInfo?
)

data class SymbolInfo(
    @SerializedName("symbol")           val symbol: String,
    @SerializedName("name")             val name: String,
    @SerializedName("lastTradedPrice")  val lastTradedPrice: Double,
    @SerializedName("change")           val change: Double,
    @SerializedName("changePercentage") val changePercentage: Double
)

data class SymbolSearchResult(
    @SerializedName("symbol") val symbol: String,
    @SerializedName("name")   val name: String
)

data class MarketSummaryResponse(
    @SerializedName("aspi")                 val aspi: Double?,
    @SerializedName("aspiChange")           val aspiChange: Double?,
    @SerializedName("aspiChangePercentage") val aspiChangePercentage: Double?
)

data class TodaySharePrice(
    @SerializedName("symbol")          val symbol: String       = "",
    @SerializedName("name")            val name: String         = "",
    @SerializedName("lastTradedPrice") val lastTradedPrice: Double = 0.0,
    @SerializedName("change")          val change: Double       = 0.0,
    @SerializedName("changePerc")      val changePerc: Double   = 0.0
)

// ── Complete CSE listed companies (286 as of Oct 2025) ───────────────────────

val CSE_ALL_COMPANIES = listOf(
    SymbolSearchResult("ABAN.N0000", "ABANS PLC"),
    SymbolSearchResult("ABFL.N0000", "ABANS FINANCE PLC"),
    SymbolSearchResult("ACL.N0000",  "ACL CABLES PLC"),
    SymbolSearchResult("ACME.N0000", "ACME PRINTING & PACKAGING PLC"),
    SymbolSearchResult("ADAM.N0000", "ADAM CAPITAL PLC"),
    SymbolSearchResult("ADFT.N0000", "ADISHAM DEVELOPMENT FINANCE PLC"),
    SymbolSearchResult("AGAL.N0000", "AGA LABORATORIES LANKA PLC"),
    SymbolSearchResult("AGST.N0000", "AGSTAR FERTILIZERS PLC"),
    SymbolSearchResult("AHPL.N0000", "ASIAN HOTELS & PROPERTIES PLC"),
    SymbolSearchResult("AHUN.N0000", "AMANA TAKAFUL LIFE PLC"),
    SymbolSearchResult("AIB.N0000",  "AMANA BANK PLC"),
    SymbolSearchResult("AICS.N0000", "AMANA INVESTMENTS PLC"),
    SymbolSearchResult("AITK.N0000", "AITKEN SPENCE PLC"),
    SymbolSearchResult("ALT.N0000",  "ALUMEX PLC"),
    SymbolSearchResult("AMSL.N0000", "AMSL LOGISTICS PLC"),
    SymbolSearchResult("ANGU.N0000", "ANGUNAKOLAPELESSA DEVELOPMENT PLC"),
    SymbolSearchResult("APLA.N0000", "ASIA PACIFIC POWER PLC"),
    SymbolSearchResult("APLL.N0000", "ASIAN PALMS INTERNATIONAL PLC"),
    SymbolSearchResult("ARAV.N0000", "ARAVALI INVESTMENTS PLC"),
    SymbolSearchResult("ARPL.N0000", "ARPITECH PLC"),
    SymbolSearchResult("ASIR.N0000", "ASIRI HOSPITAL HOLDINGS PLC"),
    SymbolSearchResult("ASIT.N0000", "ASIRI SURGICAL HOSPITAL PLC"),
    SymbolSearchResult("ASIY.N0000", "ASIRI CENTRAL HOSPITALS PLC"),
    SymbolSearchResult("ATGR.N0000", "AGALAWATTE PLANTATIONS PLC"),
    SymbolSearchResult("ATJM.N0000", "ATJM GROUP PLC"),
    SymbolSearchResult("ATKE.N0000", "AITKEN SPENCE HOTEL HOLDINGS PLC"),
    SymbolSearchResult("ATVN.N0000", "AVENTURE SRI LANKA PLC"),
    SymbolSearchResult("BALA.N0000", "BALANGODA PLANTATIONS PLC"),
    SymbolSearchResult("BANKA.N0000","BANSEI ROYAL RESORTS HIKKADUWA PLC"),
    SymbolSearchResult("BCRV.N0000", "BROWNS BEACH HOTELS PLC"),
    SymbolSearchResult("BFIN.N0000", "BIMPUTH FINANCE PLC"),
    SymbolSearchResult("BKMB.N0000", "BOGALA GRAPHITE LANKA PLC"),
    SymbolSearchResult("BLC.N0000",  "BALANGODA PLANTATIONS PLC"),
    SymbolSearchResult("BLOC.N0000", "BLUE OCEAN VENTURES PLC"),
    SymbolSearchResult("BOPL.N0000", "BOGAWANTALAWA PLANTATIONS PLC"),
    SymbolSearchResult("BPPL.N0000", "BPPL HOLDINGS PLC"),
    SymbolSearchResult("BREY.N0000", "BROWNS INVESTMENTS PLC"),
    SymbolSearchResult("BRWN.N0000", "BROWNS & COMPANY PLC"),
    SymbolSearchResult("CABO.N0000", "CARGO BOAT DEVELOPMENT COMPANY PLC"),
    SymbolSearchResult("CAL.N0000",  "CAPITAL ALLIANCE PLC"),
    SymbolSearchResult("CALT.N0000", "CEYLON AGRO INDUSTRIES PLC"),
    SymbolSearchResult("CANU.N0000", "CANWILL HOLDINGS PLC"),
    SymbolSearchResult("CARG.N0000", "CEYLON GRAIN ELEVATORS PLC"),
    SymbolSearchResult("CARS.N0000", "CARSONS CUMBERBATCH PLC"),
    SymbolSearchResult("CBUS.N0000", "COLOMBO CITY HOLDINGS PLC"),
    SymbolSearchResult("CCH.N0000",  "CEYLON COLD STORES PLC"),
    SymbolSearchResult("CCSL.N0000", "CEYLON STEEL CORPORATION PLC"),
    SymbolSearchResult("CDB.N0000",  "CITIZENS DEVELOPMENT BUSINESS FINANCE PLC"),
    SymbolSearchResult("CERA.N0000", "CEYLON CERAMICS PLC"),
    SymbolSearchResult("CFL.N0000",  "CEYLON FERTILIZER PLC"),
    SymbolSearchResult("CFVF.N0000", "CF VENTURE FUND PLC"),
    SymbolSearchResult("CGEN.N0000", "CEYLON GRAPHENE TECHNOLOGIES PLC"),
    SymbolSearchResult("CIND.N0000", "CEYLON INDUSTRIAL CORPORATION PLC"),
    SymbolSearchResult("CINS.N0000", "CEYLINCO INSURANCE PLC"),
    SymbolSearchResult("CLND.N0000", "CEYLON LAND & DEVELOPMENT PLC"),
    SymbolSearchResult("CMED.N0000", "CEYLON MEDICAL INVESTMENTS PLC"),
    SymbolSearchResult("CMF.N0000",  "CENTRAL FINANCE COMPANY PLC"),
    SymbolSearchResult("CML.N0000",  "CEYLON MOTORS PLC"),
    SymbolSearchResult("COLO.N0000", "COLOMBO FORT INVESTMENTS PLC"),
    SymbolSearchResult("COMB.N0000", "COMMERCIAL BANK OF CEYLON PLC"),
    SymbolSearchResult("CONN.N0000", "CONNAISSANCE DE CEYLAN PLC"),
    SymbolSearchResult("COOR.N0000", "CO-OPERATIVE INSURANCE COMPANY PLC"),
    SymbolSearchResult("CORT.N0000", "COROTEX INTERNATIONAL PLC"),
    SymbolSearchResult("CPC.N0000",  "CEYLON PETROLEUM CORPORATION"),
    SymbolSearchResult("CRAG.N0000", "CRAIGHEAD INVESTMENTS PLC"),
    SymbolSearchResult("CSEC.N0000", "COLOMBO STOCK EXCHANGE"),
    SymbolSearchResult("CTC.N0000",  "CEYLON TOBACCO COMPANY PLC"),
    SymbolSearchResult("CTHR.N0000", "C T HOLDINGS PLC"),
    SymbolSearchResult("CTL.N0000",  "CEYLON THEATRES PLC"),
    SymbolSearchResult("CTLK.N0000", "CEYLON TAPIOCA PLC"),
    SymbolSearchResult("CTNM.N0000", "CEYLON TAPIOCA PLC"),
    SymbolSearchResult("DALA.N0000", "DALAKOTUWA PLANTATIONS PLC"),
    SymbolSearchResult("DELT.N0000", "DELTA MANUFACTURING PLC"),
    SymbolSearchResult("DFCC.N0000", "DFCC BANK PLC"),
    SymbolSearchResult("DIAL.N0000", "DIALOG AXIATA PLC"),
    SymbolSearchResult("DIMO.N0000", "DIESEL & MOTOR ENGINEERING PLC"),
    SymbolSearchResult("DIST.N0000", "DISTILLERIES COMPANY OF SRI LANKA PLC"),
    SymbolSearchResult("DLEN.N0000", "DIPPED PRODUCTS PLC"),
    SymbolSearchResult("DPLL.N0000", "DIPPED PRODUCTS PLC"),
    SymbolSearchResult("EAST.N0000", "EASTERN MERCHANTS PLC"),
    SymbolSearchResult("EDEN.N0000", "EDEN HOTEL LANKA PLC"),
    SymbolSearchResult("EL.N0000",   "ETERNAL LAND PLC"),
    SymbolSearchResult("ELPL.N0000", "EASTERN PLAYERS PLC"),
    SymbolSearchResult("ELSO.N0000", "ELPITIYA PLANTATIONS PLC"),
    SymbolSearchResult("EML.N0000",  "ENTRUST SECURITIES PLC"),
    SymbolSearchResult("EVFL.N0000", "EVANWILL FINANCE PLC"),
    SymbolSearchResult("FACT.N0000", "FACTORY DEVELOPMENTS PLC"),
    SymbolSearchResult("FCON.N0000", "FIRST CAPITAL HOLDINGS PLC"),
    SymbolSearchResult("FHL.N0000",  "FIRST CAPITAL TREASURIES PLC"),
    SymbolSearchResult("FLAT.N0000", "FLATROCK PROPERTIES PLC"),
    SymbolSearchResult("FLCH.N0000", "FLORENCE CAPITAL PLC"),
    SymbolSearchResult("FMAM.N0000", "FM AMARATUNGA & SONS PLC"),
    SymbolSearchResult("FREE.N0000", "FREELANKA PLC"),
    SymbolSearchResult("GALE.N0000", "GALADARI HOTELS (LANKA) PLC"),
    SymbolSearchResult("GATE.N0000", "GATEWAY CERAMICS PLC"),
    SymbolSearchResult("GFT.N0000",  "GREENFERRY PROPERTIES PLC"),
    SymbolSearchResult("GLAS.N0000", "GLASSWARE LANKA PLC"),
    SymbolSearchResult("GLOB.N0000", "GLOBAL RUBBER INDUSTRIES PLC"),
    SymbolSearchResult("GMR.N0000",  "GOODHOPE ASIA HOLDINGS PLC"),
    SymbolSearchResult("GRAN.N0000", "GUARDIAN CAPITAL PARTNERS PLC"),
    SymbolSearchResult("GUAR.N0000", "GUARDIAN FUND MANAGEMENT PLC"),
    SymbolSearchResult("GULL.N0000", "GULLANDS PLC"),
    SymbolSearchResult("GUNE.N0000", "GUNEWARDENA FINANCE PLC"),
    SymbolSearchResult("HAPU.N0000", "HAPUGASTENNE PLANTATIONS PLC"),
    SymbolSearchResult("HBS.N0000",  "HBS FINANCE PLC"),
    SymbolSearchResult("HERO.N0000", "HEMAS HOLDINGS PLC"),
    SymbolSearchResult("HEXP.N0000", "HEMTOURS PLC"),
    SymbolSearchResult("HHDL.N0000", "HUNAS FALLS HOTELS PLC"),
    SymbolSearchResult("HILLS.N0000","HILLWOOD COLLEGE PLC"),
    SymbolSearchResult("HMC.N0000",  "HAYLEYS FABRIC PLC"),
    SymbolSearchResult("HNCE.N0000", "HNB FINANCE PLC"),
    SymbolSearchResult("HNB.N0000",  "HATTON NATIONAL BANK PLC"),
    SymbolSearchResult("HOPL.N0000", "HOTEL SIGIRIYA PLC"),
    SymbolSearchResult("HPFL.N0000", "HAYLEYS PLC"),
    SymbolSearchResult("HRDI.N0000", "HARBOUR VILLA PLC"),
    SymbolSearchResult("HUNA.N0000", "HUNAS FALLS HOTELS PLC"),
    SymbolSearchResult("ICAR.N0000", "ICAR LANKA PLC"),
    SymbolSearchResult("ICOF.N0000", "ICOFP PLC"),
    SymbolSearchResult("IDAL.N0000", "IDEAL FINANCE PLC"),
    SymbolSearchResult("IICT.N0000", "ISURU INVESTMENTS PLC"),
    SymbolSearchResult("IJSL.N0000", "INDUSTRIAL JANITORIAL SERVICES PLC"),
    SymbolSearchResult("IMBL.N0000", "IMB FINANCE PLC"),
    SymbolSearchResult("IMFL.N0000", "I'M CAPITAL PLC"),
    SymbolSearchResult("INSI.N0000", "INSURANCE COMPANY PLC"),
    SymbolSearchResult("ISUR.N0000", "ISURU INVESTMENTS PLC"),
    SymbolSearchResult("JAYA.N0000", "JAYAWARDENA PLANTATIONS PLC"),
    SymbolSearchResult("JKH.N0000",  "JOHN KEELLS HOLDINGS PLC"),
    SymbolSearchResult("JKHL.N0000", "JOHN KEELLS HOTELS PLC"),
    SymbolSearchResult("KALA.N0000", "KALANI AGRO PLC"),
    SymbolSearchResult("KCAB.N0000", "KELANI CABLES PLC"),
    SymbolSearchResult("KCH.N0000",  "KANDY CITY CENTRE PLC"),
    SymbolSearchResult("KDCE.N0000", "KELANI CABLES PLC"),
    SymbolSearchResult("KGAL.N0000", "KOTAGALA PLANTATIONS PLC"),
    SymbolSearchResult("KHAL.N0000", "KELSEY HOMES PLC"),
    SymbolSearchResult("KOTA.N0000", "KOTAGALA PLANTATIONS PLC"),
    SymbolSearchResult("KZOO.N0000", "KEELLS FOOD PRODUCTS PLC"),
    SymbolSearchResult("LACK.N0000", "LANKA ALUMINIUM INDUSTRIES PLC"),
    SymbolSearchResult("LACT.N0000", "LANKA CENTURY INVESTMENTS PLC"),
    SymbolSearchResult("LAND.N0000", "LAND & BUILD PLC"),
    SymbolSearchResult("LASS.N0000", "LANKA ASPHALT PLC"),
    SymbolSearchResult("LCEY.N0000", "LANKA CENTURY INVESTMENTS PLC"),
    SymbolSearchResult("LCL.N0000",  "LANKA COAL COMPANY PLC"),
    SymbolSearchResult("LCPH.N0000", "LABOOKELLIE TEA FACTORY PLC"),
    SymbolSearchResult("LFIN.N0000", "LOLC FINANCE PLC"),
    SymbolSearchResult("LGL.N0000",  "LANKA GRAPHITE PLC"),
    SymbolSearchResult("LHCL.N0000", "LOLC DEVELOPMENT FINANCE PLC"),
    SymbolSearchResult("LIOC.N0000", "LANKA IOC PLC"),
    SymbolSearchResult("LLUB.N0000", "LANKA LUBRICANTS PLC"),
    SymbolSearchResult("LMFL.N0000", "LMF HOLDINGS PLC"),
    SymbolSearchResult("LOFC.N0000", "LOLC FINANCE PLC"),
    SymbolSearchResult("LOLC.N0000", "LOLC HOLDINGS PLC"),
    SymbolSearchResult("LPH.N0000",  "LANKA PHOSPHATE PLC"),
    SymbolSearchResult("LSEC.N0000", "LOLC SECURITIES PLC"),
    SymbolSearchResult("LTGR.N0000", "LANKA TILES PLC"),
    SymbolSearchResult("LVEN.N0000", "LANKA VENTURES PLC"),
    SymbolSearchResult("LWSB.N0000", "LANKA WALLTILE PLC"),
    SymbolSearchResult("LYDS.N0000", "LYDNEY PLC"),
    SymbolSearchResult("MADU.N0000", "MADULSIMA PLANTATIONS PLC"),
    SymbolSearchResult("MALA.N0000", "MALWATTE VALLEY PLANTATIONS PLC"),
    SymbolSearchResult("MANA.N0000", "MAHAWELI ASSETS PLC"),
    SymbolSearchResult("MBAL.N0000", "MBAL PLANTATIONS PLC"),
    SymbolSearchResult("MBSL.N0000", "MERCHANT BANK OF SRI LANKA & FINANCE PLC"),
    SymbolSearchResult("MCED.N0000", "MCEDARAN PLANTATIONS PLC"),
    SymbolSearchResult("MCER.N0000", "MCEDARAN PLANTATIONS PLC"),
    SymbolSearchResult("MCKN.N0000", "MCKINNONS PLC"),
    SymbolSearchResult("MCNS.N0000", "MCNEIL INTERNATIONAL PLC"),
    SymbolSearchResult("MDF.N0000",  "MADULSIMA PLANTATIONS PLC"),
    SymbolSearchResult("MDSL.N0000", "METROMAX PROJECTS PLC"),
    SymbolSearchResult("MELS.N0000", "MELSTACORP PLC"),
    SymbolSearchResult("MFL.N0000",  "MERCHANT FINANCE PLC"),
    SymbolSearchResult("MFSL.N0000", "MULTI FINANCE PLC"),
    SymbolSearchResult("MGYL.N0000", "MAHAGAMA PLANTATIONS PLC"),
    SymbolSearchResult("MKSA.N0000", "MAHINDA RAJAPAKSA CRICKET STADIUM"),
    SymbolSearchResult("MLIP.N0000", "MOUNTAIN HAWK EXPRESS PLC"),
    SymbolSearchResult("MLTL.N0000", "MALALA AGRO FARMS PLC"),
    SymbolSearchResult("MMH.N0000",  "MODERN MERCHANTS PLC"),
    SymbolSearchResult("MONA.N0000", "MONARAWILA INVESTMENTS PLC"),
    SymbolSearchResult("MPAL.N0000", "MOUNTBATTEN PLANTATIONS PLC"),
    SymbolSearchResult("MPCT.N0000", "MULTI PACKAGING SUPPLIES PLC"),
    SymbolSearchResult("MRCH.N0000", "MERCHANTS HOLDINGS PLC"),
    SymbolSearchResult("MSEC.N0000", "MULTI SEC PLC"),
    SymbolSearchResult("MTSM.N0000", "METRITEC PLC"),
    SymbolSearchResult("MTT.N0000",  "MASKELIYA PLANTATIONS PLC"),
    SymbolSearchResult("MTUR.N0000", "MELFORT GROUP PLC"),
    SymbolSearchResult("NAMU.N0000", "NAMUUNAA INVESTMENTS PLC"),
    SymbolSearchResult("NAPL.N0000", "NANDA PLANTATIONS PLC"),
    SymbolSearchResult("NASC.N0000", "NASSCOM PLC"),
    SymbolSearchResult("NEST.N0000", "NESTLE LANKA PLC"),
    SymbolSearchResult("NFIN.N0000", "NATION LANKA FINANCE PLC"),
    SymbolSearchResult("NIB.N0000",  "NATIONAL INSURANCE COMPANY PLC"),
    SymbolSearchResult("NITT.N0000", "NITTAMBUWA INVESTMENTS PLC"),
    SymbolSearchResult("NLLC.N0000", "NALANDA LEASING PLC"),
    SymbolSearchResult("NMBF.N0000", "NMB FINANCE PLC"),
    SymbolSearchResult("NTB.N0000",  "NATIONS TRUST BANK PLC"),
    SymbolSearchResult("NTCE.N0000", "NATIONAL DEVELOPMENT BANK PLC"),
    SymbolSearchResult("NTPL.N0000", "NAMAL UNICORN FUND PLC"),
    SymbolSearchResult("OCH.N0000",  "OVERSEAS REALTY CEYLON PLC"),
    SymbolSearchResult("OFIN.N0000", "ORIENT FINANCE PLC"),
    SymbolSearchResult("ONAL.N0000", "ONALLY HOLDINGS PLC"),
    SymbolSearchResult("OSEA.N0000", "OVERSEAS REALTY CEYLON PLC"),
    SymbolSearchResult("PACK.N0000", "PACKAGING & CONTAINERS PLC"),
    SymbolSearchResult("PALM.N0000", "PALM GARDEN HOTELS PLC"),
    SymbolSearchResult("PARL.N0000", "PARAGON CEYLON PLC"),
    SymbolSearchResult("PARQ.N0000", "PARQUE PLC"),
    SymbolSearchResult("PFIN.N0000", "PEOPLE'S FINANCE PLC"),
    SymbolSearchResult("PGP.N0000",  "PEGASUS HOTELS OF CEYLON PLC"),
    SymbolSearchResult("PLAS.N0000", "PLASTIC PACKAGING PLC"),
    SymbolSearchResult("PLCH.N0000", "PELWATTE DAIRY INDUSTRIES PLC"),
    SymbolSearchResult("PNRO.N0000", "PANORAMA LANKA HOLDINGS PLC"),
    SymbolSearchResult("PRST.N0000", "PRINTCARE PLC"),
    SymbolSearchResult("PSYL.N0000", "PRASIDDHA AGRO INVESTMENTS PLC"),
    SymbolSearchResult("RACY.N0000", "RACECOURSE CASINO PLC"),
    SymbolSearchResult("RALF.N0000", "RALLIS LANKA PLC"),
    SymbolSearchResult("RAMI.N0000", "RAMBODA FALLS HOTEL PLC"),
    SymbolSearchResult("RANS.N0000", "RENUKA AGRI FOODS PLC"),
    SymbolSearchResult("RBSL.N0000", "RBS CAPITAL PLC"),
    SymbolSearchResult("REBS.N0000", "REBS PLC"),
    SymbolSearchResult("REEF.N0000", "REEF HOTEL PLC"),
    SymbolSearchResult("REXP.N0000", "RENUKA EXPORTS PLC"),
    SymbolSearchResult("RGEM.N0000", "ROYAL GEMS & JEWELLERY PLC"),
    SymbolSearchResult("RICH.N0000", "RICHARD PIERIS & COMPANY PLC"),
    SymbolSearchResult("RINS.N0000", "RENUKA INSURANCE BROKERS PLC"),
    SymbolSearchResult("RKSH.N0000", "RENUKA CITY HOTELS PLC"),
    SymbolSearchResult("RPLY.N0000", "ROHINI PLANTATIONS PLC"),
    SymbolSearchResult("RPUR.N0000", "RAIGAM SALTERNS PLC"),
    SymbolSearchResult("RREE.N0000", "REAL ESTATE & DEVELOPMENT PLC"),
    SymbolSearchResult("RWSL.N0000", "REGNIS (LANKA) PLC"),
    SymbolSearchResult("SALG.N0000", "SALICINE GROUP PLC"),
    SymbolSearchResult("SALL.N0000", "SALLYS INVESTMENTS PLC"),
    SymbolSearchResult("SAMP.N0000", "SAMPATH BANK PLC"),
    SymbolSearchResult("SANG.N0000", "SANGRAAMA PLC"),
    SymbolSearchResult("SANT.N0000", "SANMUGAM HOLDINGS PLC"),
    SymbolSearchResult("SASA.N0000", "SASSERUWA HOTELS PLC"),
    SymbolSearchResult("SCAP.N0000", "SEYLAN BANK PLC"),
    SymbolSearchResult("SCBL.N0000", "STANDARD CHARTERED BANK"),
    SymbolSearchResult("SEIC.N0000", "SEYCHELLES ISLAND CONTINENTAL PLC"),
    SymbolSearchResult("SEMB.N0000", "SEYLAN MERCHANT BANK PLC"),
    SymbolSearchResult("SERV.N0000", "ODEL PLC"),
    SymbolSearchResult("SEYB.N0000", "SEYLAN BANK PLC"),
    SymbolSearchResult("SFIN.N0000", "SEYLAN DEVELOPMENT PLC"),
    SymbolSearchResult("SGBL.N0000", "SINGHE HOSPITALS PLC"),
    SymbolSearchResult("SHAL.N0000", "SHAW WALLACE CEYLON PLC"),
    SymbolSearchResult("SHOT.N0000", "SHOGUN HOLDINGS PLC"),
    SymbolSearchResult("SIGA.N0000", "SIGIRIYA VILLAGE HOTELS PLC"),
    SymbolSearchResult("SINT.N0000", "SINTERCOM LANKA PLC"),
    SymbolSearchResult("SJMS.N0000", "SRI LANKA TELECOM PLC"),
    SymbolSearchResult("SKAD.N0000", "SKANDAGIRI TEA FACTORY PLC"),
    SymbolSearchResult("SLIT.N0000", "SRI LANKA INSTITUTE OF TEXTILE & APPAREL"),
    SymbolSearchResult("SLND.N0000", "SRILANKAN AIRLINES PLC"),
    SymbolSearchResult("SLTL.N0000", "SRI LANKA TELECOM PLC"),
    SymbolSearchResult("SMBL.N0000", "SAMAGI MUTUAL BENEFIT PLC"),
    SymbolSearchResult("SMF.N0000",  "SWARNAMAHAL FINANCIAL SERVICES PLC"),
    SymbolSearchResult("SOFT.N0000", "SOFTLOGIC HOLDINGS PLC"),
    SymbolSearchResult("SOFL.N0000", "SOFTLOGIC FINANCE PLC"),
    SymbolSearchResult("SOLI.N0000", "SOFTLOGIC LIFE INSURANCE PLC"),
    SymbolSearchResult("SOLR.N0000", "SOLAR INDUSTRIES LANKA PLC"),
    SymbolSearchResult("SPEN.N0000", "AITKEN SPENCE PLC"),
    SymbolSearchResult("SPIN.N0000", "SPINTEX CEYLON PLC"),
    SymbolSearchResult("SPUR.N0000", "SPURGEON PLC"),
    SymbolSearchResult("SSMH.N0000", "SSMC HOLDINGS PLC"),
    SymbolSearchResult("SSML.N0000", "SSMC HOLDINGS PLC"),
    SymbolSearchResult("STRN.N0000", "STERLING INVESTMENT PLC"),
    SymbolSearchResult("SUGA.N0000", "SUGAR INDUSTRIES OF CEYLON PLC"),
    SymbolSearchResult("SUNW.N0000", "SUNWAY CONSTRUCTION PLC"),
    SymbolSearchResult("SWAD.N0000", "SWADESHI INDUSTRIAL WORKS PLC"),
    SymbolSearchResult("SWER.N0000", "SWISSTEK CEYLON PLC"),
    SymbolSearchResult("SWIS.N0000", "SWISSTEK (CEYLON) PLC"),
    SymbolSearchResult("TAFL.N0000", "TALAWAKELLE TEA ESTATES PLC"),
    SymbolSearchResult("TALF.N0000", "TALAWAKELLE TEA ESTATES PLC"),
    SymbolSearchResult("TAMA.N0000", "TAM PLC"),
    SymbolSearchResult("TAYO.N0000", "TAYO CIRCUITS PLC"),
    SymbolSearchResult("TCFL.N0000", "TEXTURED JERSEY CEYLON PLC"),
    SymbolSearchResult("TCSL.N0000", "THREE COINS PLC"),
    SymbolSearchResult("TFAC.N0000", "THE FORTRESS RESORT & SPA PLC"),
    SymbolSearchResult("TILO.N0000", "TIMEX GARMENTS PLC"),
    SymbolSearchResult("TJSL.N0000", "TEXTURED JERSEY LANKA PLC"),
    SymbolSearchResult("TJL.N0000",  "TEXTURED JERSEY LANKA PLC"),
    SymbolSearchResult("TKCM.N0000", "TALAWAKELE TEA ESTATES PLC"),
    SymbolSearchResult("TLCE.N0000", "TELECOM LANKA PLC"),
    SymbolSearchResult("TMX.N0000",  "TIGER MEDIA GROUP PLC"),
    SymbolSearchResult("TPLA.N0000", "TOUCHWOOD INVESTMENTS PLC"),
    SymbolSearchResult("TRAN.N0000", "TRANSPARAN PLC"),
    SymbolSearchResult("TREN.N0000", "TREND LANKA PLC"),
    SymbolSearchResult("TSDA.N0000", "TESS AGRO PLC"),
    SymbolSearchResult("TSTM.N0000", "TIMEX GROUP PLC"),
    SymbolSearchResult("TUCK.N0000", "TUCKER COMPANY PLC"),
    SymbolSearchResult("UDPL.N0000", "UNION DEVELOPMENT PROJECTS PLC"),
    SymbolSearchResult("UNIOA.N0000","UNION ASSURANCE PLC"),
    SymbolSearchResult("UNIOB.N0000","UNION ASSURANCE PLC"),
    SymbolSearchResult("VAID.N0000", "VAIDS INVESTMENTS PLC"),
    SymbolSearchResult("VALE.N0000", "VALLIBEL FINANCE PLC"),
    SymbolSearchResult("VALF.N0000", "VALLIBEL FINANCE PLC"),
    SymbolSearchResult("VALL.N0000", "VALLIBEL ONE PLC"),
    SymbolSearchResult("VICT.N0000", "VICTORIA GOLF & COUNTRY RESORT PLC"),
    SymbolSearchResult("VLLB.N0000", "VALLIBEL ONE PLC"),
    SymbolSearchResult("VPFL.N0000", "VIDULLANKA PLC"),
    SymbolSearchResult("VPVG.N0000", "VIVANTA INVESTMENTS PLC"),
    SymbolSearchResult("WATT.N0000", "WATAWALA PLANTATIONS PLC"),
    SymbolSearchResult("WFIN.N0000", "WING FOOK FINANCE PLC"),
    SymbolSearchResult("WIND.N0000", "WINDFORCE PLC"),
    SymbolSearchResult("WISH.N0000", "WISHFORD INVESTMENTS PLC"),
    SymbolSearchResult("WRDL.N0000", "WINDFORCE PLC"),
    SymbolSearchResult("YORK.N0000", "YORK ARCADE HOLDINGS PLC")
)

// Keep small fallback alias pointing to full list
val CSE_POPULAR = CSE_ALL_COMPANIES
